### ISSUE TITLE
service-wrapper unable to handle spaces in Java path

### ISSUE THREAD

**Issue by gusarov** [openhab/openhab-distro#830]
I just installed OpenHAB as a Windows Service following instructions (service-wrapper)
The wrapper.log file clearly indicates that service wrapper unable to handle spaces in path.
Java is installed by default in default location, so, it contains spaces.

STATUS | wrapper  | 2018/12/21 22:18:20 | openHAB2 installed.
STATUS | wrapper  | 2018/12/21 22:19:31 | --> Wrapper Started as Service
STATUS | wrapper  | 2018/12/21 22:19:31 | Launching a JVM...
INFO   | jvm 1    | 2018/12/21 22:19:31 | Error: Could not find or load main class **Files\Java\jre1.8.0_191**\.jre.lib.endorsed;**c:\Program**
ERROR  | wrapper  | 2018/12/21 22:19:31 | JVM exited while loading the application.

**Comment by wborn** [comment]
I read a few days ago it's a know Karaf issue [KARAF-5908](https://issues.apache.org/jira/browse/KARAF-5908) and fixed in Karaf 4.2.2.

**Comment by gusarov** [comment]
I've download http://www.apache.org/dyn/closer.lua/karaf/4.2.2/apache-karaf-4.2.2.zip
and replaced the content of "openHab\Runtime" content with this zip archive content.
Service is not starting, still the same error in log.

**Comment by gusarov** [comment]
I've tried all combinations of quotes and backslash in java_home
if I remove tailing slash, there is another error:
 Error: Could not find or load main class org.apache.karaf.wrapper.internal.service.Main

**Comment by wborn** [comment]
Did you also give the new Karaf 4.2.2 based snapshot a try [openhab-2.5.0-SNAPSHOT.zip](https://ci.openhab.org/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-2.5.0-SNAPSHOT.zip)?
